GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "rest client post",
    "author": "rest pro",
    "url": "fakeurl",
    "likes": "9"
}
